name = "oglegacyv3"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "oglegacy-db"
database_id = "VOTRE-DATABASE-ID"

[[r2_buckets]]
binding = "R2"
bucket_name = "oglegacy-media"