name = "NOM-WORKER"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "NOM-DB"
database_id = "VOTRE-DATABASE-ID"

[[r2_buckets]]
binding = "R2"
bucket_name = "NOM-media"